export type GradeCollection = {
  preK: number,
  k: number,
  ['1']: number,
  ['2']: number,
  ['3']: number,
  ['4']: number,
  ['5']: number,
  ['6']: number,
  ['7']: number,
  ['8']: number,
  ['9']: number,
  ['10']: number,
  ['11']: number,
  ['12']: number,
  sp: number,
};
export type SchoolData = {
  name: string,
  address: string,
  grades: string,
  principal: string,
  neighborhood: string,
  typology: string,
  educationalProgram: string,
  squareFeet: number,
  totalStudents: number,
  totalEnergyCost: number,
  studentsByGrade: GradeCollection,
  accessibility: {
    playAreas: string,
    accessibility: string,
    parkingQuality: string,
    massTransit: string,
    bikable: string,
    walkable: string,
    dropOffPickUp: string,
    adaAccessibility: string,
  },
  features: {
    playgrounds: string,
    accessible: string,
    playFields: string,
  },
  adequacy: {
    elementary: {
      art: string,
      music: string,
      gymnasium: string,
      cafeteria: string,
      stage: string,
    },
    middle: {
      art: string,
      music: string,
      gymnasium: string,
      cafeteria: string,
      stage: string,
    },
    high: {
      art: string,
      music: string,
      gymnasium: string,
      cafeteria: string,
      stage: string,
    },
  },
};

export default SchoolData;
